### ISSUE TITLE
string response is nil 

### ISSUE THREAD

**Issue by zvanderbilt** [hasanen/wpcli#1]
Siteurl is not getting returned after "option get siteurl". This happens with blogname and probably any other commands that return a string. I confirmed running "wp option get siteurl" directly did correctly return the siteurl and blogname.

**Comment by hasanen** [comment]
Hi @zvanderbilt, thanks for reporting the issue.

What version of Wordpress are you using?

**Comment by zvanderbilt** [comment]
That specific instance was using version 4.4.2. 

I have also observed it on the current version 4.5.

**Comment by hasanen** [comment]
Thank you. I'll have a look at this and get back to you when I know more.

**Comment by hasanen** [comment]
@zvanderbilt This is now fixed in version `0.2.9`.
